Replace setup Ruby action.
BECAUSE...

Run actions/setup-ruby@v1
  with:
    ruby-version: 3.0.2
------------------------
NOTE: This action is deprecated and is no longer maintained.
Please, migrate to https://github.com/ruby/setup-ruby, which is being actively maintained.
------------------------
Error: Version 3.0.2 not found